logging.level.root=info

## =============================================
## === [Eureka Client Registration Settings] ===
## =============================================

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.response-cache-update-interval-ms=30000
eureka.instance.prefer-ip-address=false

## ==================================================
## === [Eureka Server Connection & Auth Settings] ===
## ==================================================

spring.security.user.name=${EUREKA_USERNAME}
spring.security.user.password=${EUREKA_PASSWORD}
eureka.port=${server.port}

eureka.url=http://${spring.security.user.name}:${spring.security.user.password}@localhost:${eureka.port}/eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:${eureka.url}}
